### ISSUE TITLE
Can't be used in XYZ plot for some reason.

### ISSUE THREAD

**Issue by songib** [light-and-ray/sd-webui-lcm-sampler#2]
But no big deal I guess. xd

**Comment by light-and-ray** [comment]
Hm, inside readme file I used xyz plot

**Comment by songib** [comment]
@light-and-ray I'll try it again. Maybe I need to restart the CMD. ty

**Comment by dani2191** [comment]
I was having the same issue so I'll share what I did just in case anybody else is having trouble making it work.
Of course, the first thing I tried was reloading Web-UI and restarting Web-UI, but that did not help, So after that I decided to go to the extension's scripts folder, opened lcm-sampler.py and changed `NAME = 'LCM Test'` to `NAME = 'LCM'`, saved, restarted Web-UI and XYZ plot worked just fine.
